services:
  redis-eitaa:
    image: redis:8.8.0-alpine3.23
    restart: unless-stopped
    container_name: redis-eitaa
    network_mode: "service:nginx-redis"
    volumes:
    - redis-data:/data
    - ./redis/redis-eitaa.conf:/etc/redis/redis.conf:ro
    healthcheck:
      test: ["CMD", "redis-cli", "SET", "test:$(date +%s)", "success"]
      interval: 2s
      timeout: 3s
      retries: 5

  nginx-redis:
    image: nginx:1.31.1-trixie
    restart: unless-stopped
    container_name: nginx-redis
    volumes:
    - ./nginx/nginx-redis.conf:/etc/nginx/nginx.conf:ro
    ports:
    - "9000:9000"
    healthcheck:
      test: ["CMD", "pidof", "nginx"]
      interval: 2s
      timeout: 3s
      retries: 5

volumes:
  redis-data:
