events {
    worker_connections 1024;
}

stream {
    upstream redis_backend {
        server 127.0.0.1:6379;
    }

    server {
        listen 9000;
        proxy_pass redis_backend;
        proxy_connect_timeout 5s;
        proxy_timeout 30s;
    }
}
