services:
  backend1:
    restart: unless-stopped
    container_name: backend1
    build:
      context: backend/
    networks:
    - eitaa-network
    environment:
      SERVER_ID: 1
    healthcheck:
      test: ["CMD-SHELL", "wget -q -O- http://127.0.0.1:8000 || exit 1"]
      interval: 2s
      timeout: 1s
      retries: 3

  backend2:
    restart: unless-stopped
    container_name: backend2
    build:
      context: backend/
    networks:
    - eitaa-network
    environment:
      SERVER_ID: 2
    healthcheck:
      test: ["CMD-SHELL", "wget -q -O- http://127.0.0.1:8000 || exit 1"]
      interval: 2s
      timeout: 1s
      retries: 3

  nginx:
    restart: unless-stopped
    depends_on:
    - backend1
    - backend2
    container_name: nginx-eitaa
    build:
      context: nginx/
    ports:
    - "8080:8080"
    networks:
    - eitaa-network
    environment:
      LB_TYPE: ${LB_TYPE:-NGINX}
    healthcheck:
      test: ["CMD-SHELL", "curl http://127.0.0.1:8080 | grep -q -E '1|2' || exit 1"]
      interval: 2s
      timeout: 1s
      retries: 3

networks:
  eitaa-network:
    driver: bridge
