include:
- ../2-SafeRedis/compose.yaml

services:
  redis-exporter:
    image: oliver006/redis_exporter:v1.86.0-alpine
    restart: unless-stopped
    container_name: redis-exporter
    depends_on:
    - redis-eitaa
    - nginx-redis
    network_mode: "service:nginx-redis"
    environment:
      REDIS_ADDR: ${REDIS_ADDR}
      REDIS_EXPORTER_BASIC_AUTH_USERNAME: ${REDIS_EXPORTER_BASIC_AUTH_USERNAME}
      REDIS_EXPORTER_BASIC_AUTH_PASSWORD: ${REDIS_EXPORTER_BASIC_AUTH_PASSWORD}
    healthcheck:
      test: ["CMD-SHELL", "wget  http://$$REDIS_EXPORTER_BASIC_AUTH_USERNAME:$$REDIS_EXPORTER_BASIC_AUTH_PASSWORD@localhost:9121/health -q -O - || exit 1"]
      interval: 2s
      timeout: 3s
      retries: 5

networks:
  eitaa-network:
    driver: bridge
