{
 "title": "Redis Monitoring",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Memory Usage",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(redis_memory_used_bytes / redis_memory_max_bytes) * 100\r\n\r\n",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Uptime",
   "type": "stat",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "redis_uptime_in_seconds\r\n", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Connected Clients",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 0 },
   "targets": [
    { "expr": "redis_connected_clients", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Commands/sec",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "rate(redis_commands_processed_total[1m])\r\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Cache Hit Ratio",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(redis_keyspace_hits_total / (redis_keyspace_hits_total + redis_keyspace_misses_total)) * 100\r\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Key Count",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    { "expr": "sum(redis_db_keys)\r\n", "legendFormat": "__auto" }
   ]
  },
  { "title": "Redis", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 16 } }
 ]
}